// Import task types and models
import {
  OPENAI,
  COHERE,
  HUGGINGFACE,
  ANTHROPIC,
  MISTRAL,
  GEMINI,
  GROK,
  RESEARCH_ANALYSIS,
  MESSAGE_PROCESSING,
  UPLOAD_FILE,
  FILE_RETRIEVAL,
  ORGANIZE_FILES,
  FINANCE_ANALYSIS,
  SEND_EMAIL,
  FETCH_UNREAD_EMAILS,
  SUMMARIZE_EMAILS,
  SEARCH_EMAILS,
  MEETING_SCHEDULING,
  FETCH_UPCOMING_EVENTS,
  MARKET_RESEARCH,
  QUICK_ANSWERS,
  REPORT_GENERATION,
  PROGRESS_TRACKING,
  HEALTH_REMINDERS,
} from "./constants.js";

// task to model mapping
const TASK_MODEL_MAPPING = {
  [RESEARCH_ANALYSIS]: HUGGINGFACE,
  [MESSAGE_PROCESSING]: OPENAI,
  // [UPLOAD_FILE]: GROK,
  // [FILE_RETRIEVAL]: GROK,
  // [ORGANIZE_FILES]: MISTRAL,
  [FINANCE_ANALYSIS]: HUGGINGFACE,
  [SEND_EMAIL]: ANTHROPIC,
  // [FETCH_UNREAD_EMAILS]: ANTHROPIC,
  [SUMMARIZE_EMAILS]: GEMINI,
  // [SEARCH_EMAILS]: OPENAI,
  // [MEETING_SCHEDULING]: OPENAI,
  // [FETCH_UPCOMING_EVENTS]: MISTRAL,
  [MARKET_RESEARCH]: HUGGINGFACE,
  [QUICK_ANSWERS]: GEMINI,
  [REPORT_GENERATION]: COHERE,
  [PROGRESS_TRACKING]: GEMINI,
  [HEALTH_REMINDERS]: ANTHROPIC,
};

// Get the best AI model for a specific task.
export const getModelForTask = (taskType) => {
  return TASK_MODEL_MAPPING[taskType] || OPENAI;
};
